{% set name = "pandas-datareader" %}
{% set version = "0.5.0" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "7523ca480c258cf4335869ba72e201807f2f3a8f4395efad5508a269efff18c9" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

requirements:
  build:
    - python
    - setuptools
    - pandas >=0.17.0,<0.19
    - requests >=2.3.0
    - requests-file
    - requests-ftp
  run:
    - python
    - pandas >=0.17.0,<0.19
    - requests >=2.3.0
    - requests-file
    - requests-ftp

test:
  imports:
    - pandas_datareader
    - pandas_datareader.compat
    - pandas_datareader.google
    - pandas_datareader.io
    - pandas_datareader.tests
    - pandas_datareader.tests.google
    - pandas_datareader.tests.io
    - pandas_datareader.tests.yahoo
    - pandas_datareader.yahoo

about:
  home: https://github.com/pydata/pandas-datareader
  license: BSD License
  license_family: BSD
  license_file: ''
  summary: Data readers extracted from the pandas codebase,should be compatible with recent pandas versions
  description: "pandas-datareader\n=================\n\nUp to date remote data access for pandas, works for multiple versions of pandas.\n\n.. image:: https://img.shields.io/pypi/v/pandas-datareader.svg\n\
    \    :target: https://pypi.python.org/pypi/pandas-datareader/\n    \n.. image:: https://img.shields.io/pypi/dm/pandas-datareader.svg\n    :target: https://pypi.python.org/pypi/pandas-datareader/\n\n\
    .. image:: https://travis-ci.org/pydata/pandas-datareader.svg?branch=master\n    :target: https://travis-ci.org/pydata/pandas-datareader\n\n.. image:: https://coveralls.io/repos/pydata/pandas-datareader/badge.svg?branch=master\n\
    \    :target: https://coveralls.io/r/pydata/pandas-datareader\n\n.. image:: https://readthedocs.org/projects/pandas-datareader/badge/?version=latest\n    :target: https://pandas-datareader.readthedocs.io/en/latest/\n\
    \n.. image:: https://landscape.io/github/pydata/pandas-datareader/master/landscape.svg?style=flat\n   :target: https://landscape.io/github/pydata/pandas-datareader/master\n   :alt: Code Health\n\nInstallation\n\
    ------------\n\n\nInstall latest release version via pip\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n\n.. code-block:: shell\n\n   $ pip install pandas-datareader\n\nInstall latest development version\n\
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n\n.. code-block:: shell\n\n    $ pip install git+https://github.com/pydata/pandas-datareader.git\n\nor\n\n.. code-block:: shell\n\n    $ git clone https://github.com/pydata/pandas-datareader.git\n\
    \    $ python setup.py install\n\nUsage\n-----\n\nStarting in 0.19.0, pandas no longer supports ``pandas.io.data`` or ``pandas.io.wb``, so\nyou must replace your imports from ``pandas.io`` with those\
    \ from ``pandas_datareader``:\n\n.. code-block:: python\n\n   from pandas.io import data, wb # becomes\n   from pandas_datareader import data, wb\n\nMany functions from the data module have been included\
    \ in the top level API.\n\n.. code-block:: python\n\n   import pandas_datareader as pdr\n   pdr.get_data_yahoo('AAPL')\n\nSee the `pandas-datareader documentation <https://pandas-datareader.readthedocs.io/>`_\
    \ for more details.\n"
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
